namespace CfApi.Native;

public enum CF_CALLBACK_TYPE : uint
{
    CF_CALLBACK_TYPE_FETCH_DATA = 0,
    CF_CALLBACK_TYPE_VALIDATE_DATA = 1,
    CF_CALLBACK_TYPE_CANCEL_FETCH_DATA = 2,
    CF_CALLBACK_TYPE_FETCH_PLACEHOLDERS = 3,
    CF_CALLBACK_TYPE_CANCEL_FETCH_PLACEHOLDERS = 4,
    CF_CALLBACK_TYPE_NOTIFY_FILE_OPEN_COMPLETION = 5,
    CF_CALLBACK_TYPE_NOTIFY_FILE_CLOSE_COMPLETION = 6,
    CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE = 7,
    CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE_COMPLETION = 8,
    CF_CALLBACK_TYPE_NOTIFY_DELETE = 9,
    CF_CALLBACK_TYPE_NOTIFY_DELETE_COMPLETION = 10,
    CF_CALLBACK_TYPE_NOTIFY_RENAME = 11,
    CF_CALLBACK_TYPE_NOTIFY_RENAME_COMPLETION = 12,
    CF_CALLBACK_TYPE_NONE = 0xFFFFFFFF
}

[Flags]
public enum CF_REGISTER_FLAGS : uint
{
    CF_REGISTER_FLAG_NONE = 0,
    CF_REGISTER_FLAG_UPDATE = 1,
    CF_REGISTER_FLAG_DISABLE_ON_DEMAND_POPULATION_ROOT_DIRECTORY = 2,
    CF_REGISTER_FLAG_MARK_IN_SYNC_ON_ROOT = 4
}

[Flags]
public enum CF_CONNECT_FLAGS : uint
{
    CF_CONNECT_FLAG_NONE = 0,
    CF_CONNECT_FLAG_REQUIRE_PROCESS_INFO = 0x2,
    CF_CONNECT_FLAG_REQUIRE_FULL_FILE_PATH = 0x4,
    CF_CONNECT_FLAG_BLOCK_SELF_IMPLICIT_HYDRATION = 0x8
}

public enum CF_HYDRATION_POLICY_PRIMARY : uint
{
    CF_HYDRATION_POLICY_PARTIAL = 0,
    CF_HYDRATION_POLICY_PROGRESSIVE = 1,
    CF_HYDRATION_POLICY_FULL = 2,
    CF_HYDRATION_POLICY_ALWAYS_FULL = 3
}

[Flags]
public enum CF_HYDRATION_POLICY_MODIFIER : uint
{
    CF_HYDRATION_POLICY_MODIFIER_NONE = 0,
    CF_HYDRATION_POLICY_MODIFIER_VALIDATION_REQUIRED = 1,
    CF_HYDRATION_POLICY_MODIFIER_STREAMING_ALLOWED = 2,
    CF_HYDRATION_POLICY_MODIFIER_AUTO_DEHYDRATION_ALLOWED = 4
}

public enum CF_POPULATION_POLICY_PRIMARY : uint
{
    CF_POPULATION_POLICY_PARTIAL = 0,
    CF_POPULATION_POLICY_FULL = 1,
    CF_POPULATION_POLICY_ALWAYS_FULL = 2
}

[Flags]
public enum CF_POPULATION_POLICY_MODIFIER : uint
{
    CF_POPULATION_POLICY_MODIFIER_NONE = 0
}

[Flags]
public enum CF_INSYNC_POLICY : uint
{
    CF_INSYNC_POLICY_NONE = 0,
    CF_INSYNC_POLICY_TRACK_FILE_CREATION_TIME = 0x01,
    CF_INSYNC_POLICY_TRACK_FILE_READ_ONLY_ATTRIBUTE = 0x02,
    CF_INSYNC_POLICY_TRACK_FILE_HIDDEN_ATTRIBUTE = 0x04,
    CF_INSYNC_POLICY_TRACK_FILE_SYSTEM_ATTRIBUTE = 0x08,
    CF_INSYNC_POLICY_TRACK_DIRECTORY_CREATION_TIME = 0x10,
    CF_INSYNC_POLICY_TRACK_DIRECTORY_READ_ONLY_ATTRIBUTE = 0x20,
    CF_INSYNC_POLICY_TRACK_DIRECTORY_HIDDEN_ATTRIBUTE = 0x40,
    CF_INSYNC_POLICY_TRACK_DIRECTORY_SYSTEM_ATTRIBUTE = 0x80,
    CF_INSYNC_POLICY_TRACK_FILE_LAST_WRITE_TIME = 0x100,
    CF_INSYNC_POLICY_TRACK_DIRECTORY_LAST_WRITE_TIME = 0x200,
    CF_INSYNC_POLICY_PRESERVE_INSYNC_FOR_SYNC_ENGINE = 0x80000000,
    CF_INSYNC_POLICY_TRACK_ALL = 0x7FFFFFFF
}

public enum CF_HARDLINK_POLICY : uint
{
    CF_HARDLINK_POLICY_NONE = 0,
    CF_HARDLINK_POLICY_ALLOWED = 1
}

public enum CF_PLACEHOLDER_MANAGEMENT_POLICY : uint
{
    CF_PLACEHOLDER_MANAGEMENT_POLICY_DEFAULT = 0,
    CF_PLACEHOLDER_MANAGEMENT_POLICY_CONVERT_TO_UNRESTRICTED = 1
}

public enum CF_OPERATION_TYPE : uint
{
    CF_OPERATION_TYPE_TRANSFER_DATA = 0,
    CF_OPERATION_TYPE_RETRIEVE_DATA = 1,
    CF_OPERATION_TYPE_ACK_DATA = 2,
    CF_OPERATION_TYPE_RESTART_HYDRATION = 3,
    CF_OPERATION_TYPE_TRANSFER_PLACEHOLDERS = 4,
    CF_OPERATION_TYPE_ACK_DEHYDRATE = 5,
    CF_OPERATION_TYPE_ACK_DELETE = 6,
    CF_OPERATION_TYPE_ACK_RENAME = 7
}

[Flags]
public enum CF_PLACEHOLDER_CREATE_FLAGS : uint
{
    CF_PLACEHOLDER_CREATE_FLAG_NONE = 0,
    CF_PLACEHOLDER_CREATE_FLAG_DISABLE_ON_DEMAND_POPULATION = 1,
    CF_PLACEHOLDER_CREATE_FLAG_MARK_IN_SYNC = 2,
    CF_PLACEHOLDER_CREATE_FLAG_SUPERSEDE = 4,
    CF_PLACEHOLDER_CREATE_FLAG_ALWAYS_FULL = 8
}

[Flags]
public enum CF_CREATE_FLAGS : uint
{
    CF_CREATE_FLAG_NONE = 0,
    CF_CREATE_FLAG_STOP_ON_ERROR = 1
}

[Flags]
public enum CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAGS : uint
{
    CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_NONE = 0,
    CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_STOP_ON_ERROR = 1,
    CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_DISABLE_ON_DEMAND_POPULATION = 2
}

[Flags]
public enum CF_OPERATION_TRANSFER_DATA_FLAGS : uint
{
    CF_OPERATION_TRANSFER_DATA_FLAG_NONE = 0
}

[Flags]
public enum CF_OPERATION_ACK_DELETE_FLAGS : uint
{
    CF_OPERATION_ACK_DELETE_FLAG_NONE = 0
}

[Flags]
public enum CF_OPERATION_ACK_RENAME_FLAGS : uint
{
    CF_OPERATION_ACK_RENAME_FLAG_NONE = 0
}

[Flags]
public enum CF_CALLBACK_FETCH_DATA_FLAGS : uint
{
    CF_CALLBACK_FETCH_DATA_FLAG_NONE = 0,
    CF_CALLBACK_FETCH_DATA_FLAG_RECOVERY = 1,
    CF_CALLBACK_FETCH_DATA_FLAG_EXPLICIT_HYDRATION = 2
}

[Flags]
public enum CF_CALLBACK_FETCH_PLACEHOLDERS_FLAGS : uint
{
    CF_CALLBACK_FETCH_PLACEHOLDERS_FLAG_NONE = 0
}

public enum CF_CALLBACK_DEHYDRATION_REASON : uint
{
    CF_CALLBACK_DEHYDRATION_REASON_NONE = 0,
    CF_CALLBACK_DEHYDRATION_REASON_USER_MANUAL = 1,
    CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_LOW_SPACE = 2,
    CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_INACTIVITY = 3,
    CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_OS_UPGRADE = 4
}
